CREATE TABLE DATABASECHANGELOGLOCK
(
    ID          int NOT NULL,
    LOCKED      bit NOT NULL,
    LOCKGRANTED datetime2(3),
    LOCKEDBY    nvarchar(255),
    CONSTRAINT PK_DATABASECHANGELOGLOCK PRIMARY KEY NONCLUSTERED (ID) NOT ENFORCED
);
CREATE TABLE DATABASECHANGELOG
(
    ID            VARCHAR(255),
    AUTHOR        VARCHAR(255),
    FILENAME      VARCHAR(255),
    DATEEXECUTED  DATETIME,
    ORDEREXECUTED INT,
    EXECTYPE      VARCHAR(10),
    MD5SUM        VARCHAR(35),
    DESCRIPTION   VARCHAR(255),
    COMMENTS      VARCHAR(255),
    TAG           VARCHAR(255),
    LIQUIBASE     VARCHAR(20),
    CONTEXTS      VARCHAR(255),
    LABELS        VARCHAR(255),
    DEPLOYMENT_ID VARCHAR(10)
);
CREATE TABLE label
(
    id   BIGINT AUTO_INCREMENT NOT NULL,
    name VARCHAR(50) NOT NULL,
    CONSTRAINT PK_WRITER PRIMARY KEY (id)
);
